############# English navigation ##############

# main menu
[[main]]
name = "Inicial"
url = "/"
weight = 1

[[main]]
name = "Sobre"
url = "sobre/"
weight = 2

[[main]]
parent = "Extra"
name = "Blog"
url = "blog/"

[[main]]
parent = "Extra"
name = "Contato"
url = "contato/"

# footer menu
[[footer]]
name = "Sobre"
url = "sobre/"
weight = 1

[[footer]]
name = "Politica de Privacidade"
url = "privacidade/"
weight = 2