############# English navigation ##############

# main menu
[[main]]
name = "Inicial"
url = "/"
weight = 1

[[main]]
name = "Sobre"
url = "sobre/"
weight = 2

[[main]]
name = "APIs"
url = "apis/"
weight = 3

[[main]]
weight = 4
name = "Documentação"
url = "docs/"

[[main]]
parent = "Extra"
name = "Blog"
url = "blog/"

[[main]]
parent = "Extra"
name = "Contato"
url = "contato/"

# footer menu
[[footer]]
name = "Sobre"
url = "sobre/"
weight = 1

[[footer]]
name = "APIs"
url = "apis/"
weight = 2

[[footer]]
name = "Politica de Privacidade"
url = "privacidade/"
weight = 3
