############# English navigation ##############

# main menu
[[main]]
name = "Inicial"
url = "/"
weight = 1

[[main]]
name = "Sobre"
url = "sobre/"
weight = 2

[[main]]
name = "Contato"
url = "contato/"
weight = 3

# footer menu
[[footer]]
name = "Sobre"
url = "sobre/"
weight = 1

[[footer]]
name = "Contato"
url = "contato/"
weight = 2